Repository MicrosoftDocs/windows-dev-docs, pull requests merged in 2019-08, with the labels that each got.

#1844 Typofix "we're can't"
  windows-apps-src/get-started/get-started-tutorial-game-js2d.md
Labels: Change sent to author, do-not-merge

#1846 Edit pass: Capture photos and video with Windows built-in camera UI
  windows-apps-src/audio-video-camera/capture-photos-and-video-with-cameracaptureui.md
Labels: Change sent to author, do-not-merge

#1849 Add FAQ for the redirector app
  hub/python/faqs.md
Labels: Change sent to author, do-not-merge, hub/tech, windows/prod

#1852 Fix FlipView Url issue
  windows-apps-src/design/input/gamepad-and-remote-interactions.md
Labels: Change sent to author, do-not-merge

#1410 Updating within how to override a default KA
  windows-apps-src/design/input/keyboard-accelerators.md
Labels: Change sent to author, do-not-merge

#1853 Update enable-your-device-for-development.md
  windows-apps-src/get-started/enable-your-device-for-development.md
Labels: Change sent to author, do-not-merge

#1854 docs: don't hard code to vs2015
  windows-apps-src/debug-test-perf/tools-for-profiling-and-performance.md
Labels: Change sent to author, assessing (C&L), do-not-merge

#1851 Fix typo
  windows-apps-src/packaging/auto-build-package-uwp-apps.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1859 Update create-an-ad-campaign-for-your-app.md
  windows-apps-src/publish/create-an-ad-campaign-for-your-app.md
Labels: Change sent to author, do-not-merge

#1789 Close code block
  hub/apps/desktop/modernize/using-the-visual-layer-with-windows-forms.md
Labels: Change sent to author, do-not-merge
