Repository MicrosoftDocs/windows-dev-docs, pull requests merged in 2019-10, with the labels that each got.

#1987 Fixed typo.
  windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md
Labels: Change sent to author, do-not-merge

#1988 Added information on unregistering printing events
  windows-apps-src/devices-sensors/print-from-your-app.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1994 Typo "Winodws" > "Windows"
  windows-apps-src/devices-sensors/pos-basics-capability.md
Labels: Change sent to author, do-not-merge

#1928 Minor updates to Windows 10 on ARM apps page
  windows-apps-src/porting/apps-on-arm.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1996 Fixed Typo
  windows-apps-src/monetize/get-subscriptions-for-a-user.md
Labels: Change sent to author, do-not-merge

#1999 Switch protocol and alias samples
  hub/apps/desktop/modernize/desktop-to-uwp-extensions.md
Labels: ready-to-merge

#2003 Corrected section title and added link
  windows-apps-src/xaml-platform/xaml-syntax-guide.md
Labels: Change sent to author, do-not-merge

#2000 Fixed typo (haders)
  windows-apps-src/gaming/change-your-shader-loading-code.md
Labels: Change sent to author, do-not-merge

#2016 Spelling.
  windows-apps-src/whats-new/windows-10-build-18362.md
Labels: Change sent to author, do-not-merge, review-team-triage

#2020 Improvements to the custom xaml winrt/c++ control documentation
  windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1968 Update MainPage.xaml.vb
  windows-apps-src/threading-async/AsyncSnippets/vbnet/MainPage.xaml.vb
Labels: assessing_(C&L), do-not-merge

#1973 Clarify collection bindings
  windows-apps-src/data-binding/data-binding-in-depth.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1976 Fix image and code
  windows-apps-src/design/basics/xaml-basics-style.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1975 Alphabetically ordered list
  windows-apps-src/design/basics/xaml-basics-adaptive-layout.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1971 Changing DateTime to DateTimeOffset for clarity
  windows-apps-src/design/app-settings/store-and-retrieve-app-data.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1960 Fixed typo.
  windows-apps-src/xaml-platform/xaml-syntax-guide.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1817 Add files via upload
  windows-apps-src/design/windows-template-studio/images/wts1.png
Labels: assessing_(C&L), do-not-merge, review-team-triage

#2010 Fix typo in the url - manage-flight-submissions.md
  windows-apps-src/monetize/manage-flight-submissions.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1883 Added missing close paren and reworked channel verbiage
  windows-apps-src/design/shell/tiles-and-notifications/firewall-allowlist-config.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1905 Add time zones
  windows-apps-src/publish/configure-precise-release-scheduling.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#2037 Fix asynchronous typos and referencing links
  windows-apps-src/cpp-and-winrt-apis/concurrency-2.md
  windows-apps-src/cpp-and-winrt-apis/concurrency.md
  windows-apps-src/cpp-and-winrt-apis/news.md
  windows-apps-src/devices-sensors/pos-basics-claim.md
  windows-apps-src/monetize/in-app-purchases-and-trials-using-the-windows-applicationmodel-store-namespace.md
Labels: Change sent to author, do-not-merge

#1998 Removed unprintable characters giving error in XAML editor
  windows-apps-src/launch-resume/run-in-the-background-indefinetly.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#2038 Variable length of UTF-8 (#2035)
  windows-apps-src/design/globalizing/use-utf8-code-page.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#2041 Fix small typos in fluent-design-system.md
  hub/apps/fluent-design-system.md
Labels: Change sent to author, do-not-merge

#2046 Fixed XAML compilation error
  windows-apps-src/debug-test-perf/optimize-xaml-loading.md
Labels: Change sent to author, do-not-merge

#2047 Use real notes for the binding page
  windows-apps-src/xaml-platform/binding-markup-extension.md
Labels: Change sent to author, do-not-merge

#2050 Improve samples
  windows-apps-src/app-resources/uri-schemes.md
  windows-apps-src/audio-video-camera/playready-encrypted-media-extension.md
  windows-apps-src/composition/inertia-modifiers.md
  windows-apps-src/composition/spring-animations.md
  windows-apps-src/contacts-and-calendar/integrating-with-contacts.md
  windows-apps-src/contacts-and-calendar/my-people-notifications.md
  windows-apps-src/debug-test-perf/app-analysis.md
  windows-apps-src/debug-test-perf/pgo-for-uwp.md
  windows-apps-src/debug-test-perf/test-with-the-emulator.md
  windows-apps-src/design/controls-and-patterns/color-picker.md
  windows-apps-src/design/controls-and-patterns/inking-controls.md
  windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md
  windows-apps-src/design/controls-and-patterns/text-handwriting-view.md
  windows-apps-src/design/input/specify-the-speech-recognizer-language.md
  windows-apps-src/devices-sensors/pos-basics-deviceobject.md
  windows-apps-src/launch-resume/declare-background-tasks-in-the-application-manifest.md
  windows-apps-src/monetize/retail-demo-experience.md
  windows-apps-src/porting/w8x-to-uwp-troubleshooting.md
  windows-apps-src/winrt-components/raising-events-in-windows-runtime-components.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#2053 Update in-proc code plugins support
  windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md
Labels: Change sent to author, assessing_(C&L), do-not-merge
