Repository MicrosoftDocs/windows-dev-docs, pull requests merged in 2020-05, with the labels that each got.

#2436 Fix broken link
  windows-apps-src/design/accessibility/accessibility-testing.md
Labels: Change sent to author, aq-pr-triaged, design/tech, ready-to-merge, uwp/prod

#2468 Include additional installer types from the v0.1 spec
  hub/package-manager/package/manifest.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2480 Add missing dash
  hub/package-manager/winget/search.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2485 Fix Typos
  hub/package-manager/package/repository.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2489 Remove extra back ticks from "git push" CMD
  hub/package-manager/package/repository.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2481 Add missing dashes
  hub/package-manager/winget/install.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2428 Fix JSON string to actually parse
  windows-apps-src/monetize/send-requests-to-the-store.md
Labels: Change sent to author, aq-pr-triaged, publish/tech, uwp/prod

#2491 TabItems is the Content property now
  windows-apps-src/design/controls-and-patterns/tab-view.md
Labels: aq-pr-triaged, do-not-merge

#2492 Update manifest.md
  hub/package-manager/package/manifest.md
Labels: Change sent to author, dev-environment/prod, do-not-merge

#2495 Corrected spelling mistake in input-injection.md
  windows-apps-src/design/input/input-injection.md
Labels: Change sent to author, design/tech, do-not-merge, uwp/prod

#2483 Fix broken link to [Guidelines for tile and icon assets] doc
  windows-apps-src/design/basics/design-and-ui-intro.md
Labels: Change sent to author, aq-pr-triaged, design/tech, do-not-merge, uwp/prod

#2482 Remove Tag option
  hub/package-manager/winget/install.md
Labels: Change sent to author, aq-pr-triaged, dev-environment/prod, do-not-merge

#2488 Update "winget list" to "winget source list"
  hub/package-manager/winget/source.md
Labels: Change sent to author, aq-pr-triaged, dev-environment/prod, do-not-merge
